export const GENRES = [
  { id: 1, name: "Comedy", type: "common" },
  { id: 2, name: "Drama", type: "common" },
  { id: 3, name: "Fantasy", type: "common" },
  { id: 4, name: "Horror", type: "common" },
  { id: 5, name: "Mystery", type: "common" },
  { id: 6, name: "Romance", type: "common" },
  { id: 7, name: "Sci-Fi", type: "common" },
  { id: 8, name: "Thriller", type: "common" },

  { id: 9, name: "Action", type: "movie_drama" },
  { id: 10, name: "Adventure", type: "movie_drama" },
  { id: 11, name: "Animation", type: "movie_drama" },
  { id: 12, name: "Biography", type: "movie_drama" },
  { id: 13, name: "Crime", type: "movie_drama" },
  { id: 14, name: "Documentary", type: "movie_drama" },
  { id: 15, name: "Family", type: "movie_drama" },
  { id: 16, name: "History", type: "movie_drama" },
  { id: 17, name: "Musical", type: "movie_drama" },
  { id: 18, name: "Sport", type: "movie_drama" },
  { id: 19, name: "War", type: "movie_drama" },
  { id: 20, name: "Western", type: "movie_drama" },

  { id: 21, name: "Fiction", type: "book" },
  { id: 22, name: "Non-Fiction", type: "book" },
  { id: 23, name: "Historical Fiction", type: "book" },
  { id: 24, name: "Self-Help", type: "book" },
  { id: 25, name: "Business", type: "book" },
  { id: 26, name: "Psychology", type: "book" },
  { id: 27, name: "Philosophy", type: "book" },
  { id: 28, name: "Science", type: "book" },
  { id: 29, name: "Poetry", type: "book" },
  { id: 30, name: "Young Adult", type: "book" },
  { id: 31, name: "Children's", type: "book" },
  { id: 32, name: "Religion", type: "book" },
  { id: 33, name: "Art & Photography", type: "book" },
]
